# Generated by Django 5.1 on 2024-08-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agriuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='agriuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='agriuser',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='agriuser',
            name='amount_of_land',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agriuser',
            name='mobile_no',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='agriuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
