# Generated by Django 5.1 on 2024-08-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_agriuser_is_active_remove_agriuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriuser',
            name='amount_of_land',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
